### ISSUE TITLE
No such file or directory: '/opt/local/bin'

### ISSUE THREAD

**Issue by rojinsafavi** [almarklein/pyelastix#15]
Any hint?

# Get params and change a few values
params = pyelastix.get_default_params()
params.MaximumNumberOfIterations = 200
params.FinalGridSpacingInVoxels = 10
​
# Apply the registration (im1 and im2 can be 2D or 3D)
im1_deformed, field = pyelastix.register(im1, im2, params)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-42-584f076ae914> in <module>()
      5 
      6 # Apply the registration (im1 and im2 can be 2D or 3D)
----> 7 im1_deformed, field = pyelastix.register(im1, im2, params)

/projects/sysbio/projects/czi/immune/anaconda2/envs/py36/lib/python3.6/site-packages/pyelastix.py in register(im1, im2, params, exact_params, verbose)
    495 
    496         # Compile command to execute
--> 497         command = [get_elastix_exes()[0],
    498                    '-m', path_im1, '-f', path_im2,
    499                    '-out', tempdir, '-p', path_params]

/projects/sysbio/projects/czi/immune/anaconda2/envs/py36/lib/python3.6/site-packages/pyelastix.py in get_elastix_exes()
    154 
    155     # Find exe
--> 156     elastix, ver = _find_executables('elastix')
    157     if elastix:
    158         base, ext = os.path.splitext(elastix)

/projects/sysbio/projects/czi/immune/anaconda2/envs/py36/lib/python3.6/site-packages/pyelastix.py in _find_executables(name)
    130     # Try harder
    131     for d in possible_locations:
--> 132         for sub in reversed(sorted(os.listdir(d))):
    133             if sub.startswith(name):
    134                 exe = os.path.join(d, sub, exe_name)

FileNotFoundError: [Errno 2] No such file or directory: '/opt/local/bin'

**Comment by mjiUST** [comment]
[solution] we need to finish the [installation process](https://github.com/almarklein/pyelastix#installation) consisting of the installation of the command-line interface `elastix`

**Comment by nauxiew** [comment]
> [solution] we need to finish the [installation process](https://github.com/almarklein/pyelastix#installation) consisting of the installation of the command-line interface `elastix`

Sorry, I am a rookie on programing, after reading the web of  elastix, I still don't know how to install the command-line interface 'elastix'. And I have occurred a lot of problems in the installation of Simpleelastix, so I choose to use pyelastix. Could anyone help me?

**Comment by mjiUST** [comment]
> > [solution] we need to finish the [installation process](https://github.com/almarklein/pyelastix#installation) consisting of the installation of the command-line interface `elastix`
> 
> Sorry, I am a rookie on programing, after reading the web of elastix, I still don't know how to install the command-line interface 'elastix'. And I have occurred a lot of problems in the installation of Simpleelastix, so I choose to use pyelastix. Could anyone help me?

It says in the README.md that 'Install this library using `conda install elastix` or `pip install pyelastix`. ' Pls have a try

**Comment by nauxiew** [comment]
> > > [solution] we need to finish the [installation process](https://github.com/almarklein/pyelastix#installation) consisting of the installation of the command-line interface `elastix`
> > 
> > 
> > Sorry, I am a rookie on programing, after reading the web of elastix, I still don't know how to install the command-line interface 'elastix'. And I have occurred a lot of problems in the installation of Simpleelastix, so I choose to use pyelastix. Could anyone help me?
> 
> It says in the README.md that 'Install this library using `conda install elastix` or `pip install pyelastix`. ' Pls have a try

really thanks for your reply, but I have used **pip install pyelastix** to install this package, but when I want to use the function like pyelastix.register(), the error  **[Errno 2] No such file or directory: '/opt/local/bin'** occurred, so I think it;s because I didn't install the command-line application of elastix, which it's mentioned in README.md. Unfortunately, I don't know how to do it.

**Comment by soupault** [comment]
To be fixed with https://github.com/almarklein/pyelastix/pull/20
