### ISSUE TITLE
average intensity & std in result image

### ISSUE THREAD

**Issue by XuLingchao** [almarklein/pyelastix#19]
Hi,

First thanks for this great toolkit to use Elastix.
Actually I face a very similar problem with @123aaron that my result image seems change the intensity distribution form the 0 to 70 to -5 to 10 approximately. 
I'm not sure this kind of normalization comes from Elastix or pyelastix and it will be helpful if you can give me some suggesstion

Thank you!

Aimyy

**Comment by soupault** [comment]
Duplicate of #6 . There might be an issue in pyelastix, indeed. I am looking into it.
