### ISSUE TITLE
RGB image registration

### ISSUE THREAD

**Issue by DamperHa** [almarklein/pyelastix#22]
Hello, is this package applicable for RGB image registration? if so, how do I set it?  Thx

**Comment by DamperHa** [comment]
Can the two pictures like the following be registered?
![1fix](https://user-images.githubusercontent.com/24379376/69237300-58d9e700-0bd0-11ea-8cd1-5c450e7bfa9d.jpg)
![2moving](https://user-images.githubusercontent.com/24379376/69237357-7b6c0000-0bd0-11ea-8ef8-7c6f5578ea69.jpg)

**Comment by almarklein** [comment]
No, the image registration needs a scalar value per pixel. You want to convert your color channels to a scalar value in a way that maximizes the structure of the resulting image.
