### ISSUE TITLE
Settings of the parameters NumberOfResolutions and MaximumNumberOfIterations？

### ISSUE THREAD

**Issue by chenyuhaosuai** [almarklein/pyelastix#25]
When I am registering, how should I set the parameters NumberOfResolutions and MaximumNumberOfIterations? To get the best results

**Comment by almarklein** [comment]
That depends on (the kind of) image data. You'd need to experiment to find a good tradeoff of parameters.

**Comment by chenyuhaosuai** [comment]
> That depends on (the kind of) image data. You'd need to experiment to find a good tradeoff of parameters.

Thank you, I have found the parameters suitable for my data image, secondly. If I want to apply the field (deformation field) to the mask image, what should I do?

**Comment by almarklein** [comment]
I think you're looking for `skimage.transform.warp`.
