### ISSUE TITLE
conda install pyelastix or elastix?

### ISSUE THREAD

**Issue by thomasaarholt** [almarklein/pyelastix#3]
Currently the conda install instruction reads `conda install elastix`. Should it not be `conda install pyelastix`

**Comment by thomasaarholt** [comment]
That feeling when you run into the same problem 1.8 years later, google for the answer and find yourself.

**Comment by BenjaminAgthe** [comment]
Hey Thomas! Did you solve it? I got the same problem^^

**Comment by thomasaarholt** [comment]
Hi! I just installed it according to my first post - conda install pyelastix

**Comment by BenjaminAgthe** [comment]
Which conda version & python version do you use!? He cannot find the pyelastix package!?

**Comment by soupault** [comment]
The available packages in Conda are not provided by us. We might take care of them in future. 

Anyway, the installation instructions have been updated - https://github.com/almarklein/pyelastix/pull/21.
